### ISSUE TITLE
Remove this module?

### ISSUE THREAD

**Issue by chillu** [silverstripe-labs/silverstripe-taggerfield#2]
@wilr @normann Do you know where this module is used? Its a very confusingly named extension of `silverstripe/tagfield`, hasn't been updated in ages, and I don't think should live under the `silverstripe-labs` vendor namespace. Since it hasn't even been added to packagist/composer, I assume usage of the module is negligible at this point.

/cc @assertchris @tractorcow

**Comment by tractorcow** [comment]
Yep let's remove this and merge this with the tagfield.

**Comment by chillu** [comment]
OK, removing.
